spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
  #          linkedin:
  #            client-id: ${LINKEDIN_CLIENT_ID}
  #            client-secret: ${LINKEDIN_CLIENT_SECRET}
  #            scope: r_liteprofile, r_emailaddress
  #            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  #            authorization-grant-type: authorization_code
  #            client-authentication-method: post
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USER}
    password: ${MAILTRAP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://testcreator-db.cyqisi4dgbgt.us-east-2.rds.amazonaws.com:1433/testcreatordb
    username: ${RDS_DB_USER}
    password: ${RDS_DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop #TODO disable this in production
    #      ddl-auto: update #TODO enable this in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: DEBUG
    org.springframework.web.filter.CorsFilter: DEBUG
    org.springframework.security: DEBUG
    root: DEBUG
    org.springframework.data: DEBUG
    org.hibernate: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  #    org.springframework.mail: DEBUG
  #    com.bsisj7.springemailauthtest.email.EmailService: DEBUG

  file:
    name: application.log


server:
  #      port: 8081
  port: 8443 # The standard HTTPS port
  #  ssl:
  #    enabled: true
  #        key-store: /etc/letsencrypt/live/3-128-51-3.nip.io/privkey.pem # Or .jks
  #    key-store: ${KEY_STORE}
  #    key-store-password: ${KEY_STORE_PASS}
  #    key-alias: ${KEY_ALIAS}
  error:
    include-message: always
    include-binding-errors: always